server:
  port: 8080

spring:
  application:
    name: chocolate-factory-api

  datasource:
    url: jdbc:mysql://localhost:3306/ceylon_chocolate_db
    username: root
    password: supun@1357
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: //
    password: //
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 86400000
    refresh-expiration: 604800000
  mail:
    from: supunmadushanka2582000@gmail.com
    from-name: Ceylon Chocolate Factory
  frontend:
    url: http://localhost:3000